### ISSUE TITLE
Filter Weights Questions

### ISSUE THREAD

**Issue by loctruong96** [danijel3/PyHTK#2]
Hello,

Thank you for publishing your work. I have a question question in regard to gen_filt.c 
so if i change frame size and stride to 
    int frameSize=44100;
    long sampPeriod=22050;
which is equivalent to 1000 ms frame size, 500ms off set, for 44100 sample per seconds.
The the gen_filt.c failed to generate the correct triangular weights. Can you be so kind of point me to the right direction? 

Thank you so much

Loc

**Comment by danijel3** [comment]
You interpreted the frameSize correctly, but sampPeriod is something different. The number 625 is equivalent to the sampling frequency of 16000 Hz. In other words the value of sampPeriod is equal to `(1e7/sampling_frequency)`. You can look at it as the length of a sample in nanoseconds, but that's irrelevant - it's just how HTK represent sampling frequency.

What you call "offset" is probably what is normally referred to as frame stride or shift. The filter doesn't have to know anything about that as it operates only in the frequency domain (it doesn't have a concept of time). This is done later (in my Python code).

Is that clear?

**Comment by danijel3** [comment]
BTW, for 44100 sampling frequency, you should set sampPeriod to roughly 227.

**Comment by loctruong96** [comment]
Ahhhh, I see, I thought sampPeriod is the same as stride or shift. Dummy me. I will make the change and see what I can get out. Thank you so much for answering my question even after 2 years of last commit!
